name: CI

# # NOTES
#
# ## GitHub Apps
#
# To use Codecov (for uploading and analyzing code coverage), you must
# authenticate the Codecov GitHub App via https://github.com/apps/codecov.
#
# ## GitHub Actions
#
# This workflow avoids the following GitHub Actions at the moment:
# - `actions-rs/cargo`: See https://github.com/actions-rs/cargo/issues/216 (Node.js 12)
# - `actions-rs/toolchain`: See https://github.com/actions-rs/toolchain/issues/219 (Node.js 12)
# - `actions-rs/tarpaulin`: This seems to be shaky, and will sometimes fail, and sometimes work.
#
# For `actions-rs/cargo` and `actions-rs/toolchain`, we instead use
# `cargo` and `rustup`  directly in the CLI instead respectively.
#
# For `actions-rs/tarpaulin`, we instead use `cargo-llvm-codecov` via
# `taiki-e/install-action@cargo-llvm-cov`.

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: build (${{ matrix.label }})
    runs-on: ubuntu-latest
    strategy:
      # Documentation:
      #  - https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
      #  - https://rust-lang.github.io/rustup/concepts/channels.html
      #  - https://rust-lang.github.io/rustup/concepts/toolchains.html
      matrix:
        include:
          - label: msrv
            toolchain: '1.70'
          - label: stable
            toolchain: stable
          - label: beta
            toolchain: beta
          - label: nightly
            toolchain: nightly

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust (${{ matrix.toolchain }})
      run: |
        rustup set profile minimal
        rustup toolchain install ${{ matrix.toolchain }}
        rustup override set ${{ matrix.toolchain }}
    - name: Print environment info
      run: |
        rustc --version --verbose
        cargo --version
        rustup --version
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: full-build-cache
    - name: Build
      run: cargo build --verbose

  test:
    name: test
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust
      run: |
        rustup set profile minimal
        rustup toolchain install nightly
        rustup override set nightly
        rustup component add llvm-tools-preview
    - name: Print environment info
      run: |
        rustc --version --verbose
        cargo --version
        rustup --version
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: full-build-cache
    - name: Install cargo-llvm-codecov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Generate code coverage
      run: |
        cargo llvm-cov \
          --all-features \
          --workspace \
          --lcov \
          --doctests \
          --output-path lcov.info
    - name: Upload code coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
        files: lcov.info

  miri:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust (nightly)
      run: |
        rustup set profile minimal
        rustup toolchain install nightly
        rustup override set nightly
        rustup component add miri
    - name: Print environment info
      run: |
        rustc --version --verbose
        cargo --version
        rustup --version
        cargo miri --version
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: full-build-cache
    - name: Setup Miri
      run: |
        cargo miri setup
    - name: Run tests with Miri
      run: cargo miri test

  # bench:
  #   name: bench
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v4
  #   - name: Install Rust
  #     run: |
  #       rustup set profile minimal
  #       rustup toolchain install stable
  #       rustup override set stable
  #   - name: Print environment info
  #     run: |
  #       rustc --version --verbose
  #       cargo --version
  #       rustup --version
  #   - name: Install Valgrind
  #     run: sudo apt install -y valgrind
  #   - name: Run benchmarks
  #     run: cargo bench --no-fail-fast

  docs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable
          rustup override set stable
      - name: Print environment info
        run: |
          rustc --version --verbose
          cargo --version
          rustup --version
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: full-build-cache
      - name: Build
        run: cargo doc --no-deps

  codequality-check:
    name: codequality-check (${{ matrix.tool }})
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        include:
          - tool: clippy
            cmd-cargo: clippy
            cmd-check: cargo fmt --all -- --check
          - tool: rustfmt
            cmd-cargo: fmt
            cmd-check: cargo clippy --all-features
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable
          rustup override set stable
          rustup component add ${{ matrix.tool }}
      - name: Print environment info
        run: |
          rustc --version --verbose
          cargo --version
          cargo ${{ matrix.cmd-cargo }} --version
          rustup --version
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: full-build-cache
      - name: Run code quality assurance check (${{ matrix.tool }})
        run: ${{ matrix.cmd-check }}

  ci-success:
    name: ci-success
    if: ${{ success() }}
    needs:
      - build
      - test
      - miri
      # - bench
      - docs
      - codequality-check
    runs-on: ubuntu-latest
    steps:
      - name: ✅ CI succeeded
        run: exit 0
